services:
  dev:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE:-UTC}
    container_name: dev_container
    hostname: ${APP_PREFIX}
    ports:
      - "${DEV_NODE_PORT:-3000}:3000"
      - "${DEV_VNC_PORT:-5901}:5901"
      - "${DEV_NOVNC_PORT:-6080}:6080"
      - "${DEV_VSCODE_PORT:-8080}:8080"
    volumes:
      - ./:/workspace
      - /workspace/node_modules
    working_dir: /workspace
    environment:
      - DISPLAY=:1
      - TZ=${TIMEZONE:-UTC}
    depends_on:
      - postgres
    command: ["./docker/dev/init.sh"]

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./:/workspace
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dev

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: devbase
      POSTGRES_USER: devbase
      POSTGRES_PASSWORD: devbase123
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_web
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: